language: python
jobs:
  include:
    - name: "Python 3.8.0 on Xenial Linux"
      python: 3.8
    - name: "Python 3.8.0 on Windows"
      os: windows
      language: shell
      before_install:
        - choco install python --version 3.8.0
        - python -m pip install --upgrade pip
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
install:
  - mkdir logs
  - mkdir ~/.pip
  - mkdir ~/pip
  - echo "" >> logs/pytest-logs.txt
  - echo "[global]">>~/.pip/pip.conf
  - echo "[global]">>~/pip/pip.ini
  - echo "extra-index-url = https://repos.libdom.net/">>~/.pip/pip.conf
  - echo "extra-index-url = https://repos.libdom.net/">>~/pip/pip.ini
  - "pip install -r requirements_test.txt"
  - "python -m spacy download da_core_news_sm"
  - "python -m spacy download da_core_news_lg"

script: pytest
