language: python
python: 3.8

matrix:
  include:
    - name: "Python 3.8.0 on Xenial Linux"
      os: linux
    - name: "Python 3.8.0 on Windows"
      os: windows
      language: sh
      before_install:
        - git clone https://github.com/pyenv-win/pyenv-win.git $HOME/.pyenv
        - export PATH="$HOME/.pyenv/pyenv-win/bin:$HOME/.pyenv/pyenv-win/shims:$PATH"
        - pyenv install -q 3.8.2
        - pyenv rehash
        - pyenv local 3.8.2
        - python --version
      env: PATH=$(pwd):/c/Python38:/c/Python38/Scripts:$PATH
before_install:
  - "export PYTHONPATH=$PYTHONPATH:$(pwd)"
install:
  - mkdir logs
  - echo "" >> logs/pytest-logs.txt
  - "pip install -r requirements.txt"
  - "python -m spacy download da_core_news_sm"
  - "python -m spacy download da_core_news_lg"

script: pytest