import lemmy.pipe
import da_core_news_lg as da
import spacy
from spacy import displacy
#import rdfCreator as creator

nlp = da.load()

# Lemmy lemmatization
pipe = lemmy.pipe.load('da')
nlp.add_pipe(pipe, after='tagger')

# Åse Andersen
#text = "Anne Lisbeth var som Melk og Blod, ung og fornøiet, deilig at see paa, Tænderne skinnede saa hvide, Øinene saa klare; Foden var let i Dandsen og Sindet endnu mere let! hvad kom der ud af det? - \"Den lede Unge!\" - ja, deilig var han ikke! han blev sat ud til Grøftegraverens Kone, Anne Lisbeth kom paa det grevelige Slot, sad i stadselig Stue med Klæder af Silke og Fløiel; ikke en Vind turde blæse paa hende, Ingen sige hende et haardt Ord, for det havde hun Skade af og det turde hun ikke taale. Hun ammede det grevelige Barn, det var fiint som en Prinds, deiligt som en Engel, hvor elskede hun dette Barn; hendes eget, ja det var i Grøftegraverens Huus, hvor ikke Gryden kogte over, men Munden kogte over, og oftest var der Ingen hjemme, Drengen græd, men hvad Ingen hører det Ingen rører, han græd sig isøvn og i Søvnen føler man ikke til Sult og Tørst, Søvnen er saadan en god Opfindelse; i Aaringer - ja, som Tiden gaaer, skyder Ukrud op, siger man, Anne Lisbeths Dreng skød op, og dog var han sat i Væxten, sagde de; men heelt var han voxet ind i Familien her, de havde faaet Penge derfor, Anne Lisbeth var ham aldeles qvit, hun var Kjøbstadmadame, havde det luunt og godt inde og Hat paa, gik hun ud, men hun gik aldrig til Grøftegraverens, det var saa langt fra Staden og hun havde der heller ikke Noget at gjøre, Drengen var deres og tære sin Kost kunde han, sagde de, Gavn for Føden skulde han gjøre, og saa passede han Mads Jensens røde Ko, han kunde nok røgte og tage sig Noget for."
# Gammel Dansk Artikel (August 1873)
#text = "Efter med nogle Ord at have dadlet Politiet for, at det, ved at lade en af sine Betjente udgive sig for ivrig Socialist og under et paataget Navn slutte sig til Geleff paa dennes Agitationsreise i Jylland, havde forført den godtroende og aabenmundede Geleff til Udtalelser der senere vare blevne anvendte imod ham, og efter i Forbigaaende at have berørt Mundbergs tvetydige Stilling til \"Internationale\" og dens Bestyrelse, gik Defensor over til det allerede tidligere i hans Foredrag berørte, kildne Punkt: Forhørsdommer Knudsens Stilling til de Anklagede. At denne ansete Dommer samvittighedsfuld havde handlet i Overensstemmelse med, hvad han selv ansaa for sin Pligt, var hævet over al Tvivl; men Defensor maatte dog betragte den af ham fulgte Fremgangsmaade som uheldig. Det var i det Hele tvivlsomt, om der burde frittes efter Tanker og Hensigter, og navnlig burde Dommeren i dette Tilfælde have handlet saa meget mere forsigtig, som han stod over for Mennesker, der ikke vare sig bevidste det Farlige i at bruge de stærke Udtryk, der nu bleve lagte dem til Last. Dommerens stærke Tro paa, at der den 5te Maj 1872 havde været forberedt et voldsomt Angreb paa den bestaaende Samfundsorden, havde aabenbart dikteret ham hans Ønske om at faa de Anklagede til at bekræfte hans Formodning i faa Henseende, og de Tilstaaelser, der bare tilførte Protokollen i dette Punkt, maatte da ogsaa i Virkeligheden siges at være Dommerens egne, af de Anklagede vedtagne Ord."
# Gammel Dansk Preprocesseret
text = "Efter med nogle Ord at have dadlet Politiet for, at det, ved at lade en af sine betjente udgive sig for ivrig socialist og under et påtaget navn slutte sig til Geleff på dennes agitationsrejse i Jylland, havde forført den godtroende og åbenmundede Geleff til udtalelser der senere vare blevne anvendte imod ham, og efter i forbigående at have berørt Mundbergs tvetydige stilling til \"Internationale\" og dens bestyrelse, gik defensor over til det allerede tidligere i hans foredrag berørte, kildne punkt: forhørsdommer Knudsens stilling til de anklagede. At denne ansete dommer samvittighedsfuld havde handlet i overensstemmelse med, hvad han selv anså for sin pligt, var hævet over al tvivl; men defensor måtte dog betragte den af ham fulgte fremgangsmåde som uheldig. Det var i det hele tvivlsomt, om der burde frittes efter tanker og hensigter, og navnlig burde dommeren i dette tilfælde have handlet så meget mere forsigtig, som han stod over for mennesker, der ikke vare sig bevidste det farlige i at bruge de stærke udtryk, der nu bleve lagte dem til last. Dommerens stærke tro på, at der den 5te Maj 1872 havde været forberedt et voldsomt angreb på den bestående samfundsorden, havde åbenbart dikteret ham hans ønske om at få de anklagede til at bekræfte hans formodning i få henseende, og de tilståelser, der bare tilførte protokollen i dette punkt, måtte da også i virkeligheden siges at være dommerens egne, af de anklagede vedtagne ord."
# Ny artikel
#text = "Aalborg har adskillige gavl- og bygningsmalerier udført i samarbejde med en billedkunstner og Techcollege i Aalborg. Men nu rykker ideen til Vrå takket været kunstner Søren Elgaard, unge fra Techcolleges skolepraktik og Kunstnersammenslutningen Vrå-udstillingen. Lærlingene fra Techcollege maler fra stilladset på gavlen af Vestergade 14. Først skal der grundes og derefter skal Søren Elgaards Lut-motiv hentet fra Vrå kirke tegnes op, så Søren Elgaard og eleverne i fællesskab kan male det. Anja Lundstrøm fra techcollege leder gruppen fra skolepraktik.   Det, de skal lave her, er en udfordring og sværere end arbejdet i virksomheder. Slutresultatet skal jo være lige så godt som Sørens skitse. De skal finde ud af, hvor mange lag maling, der skal på for at ramme den rigtige farvenuance. Vi kan jo ikke bare gå ud og købe farven i en butik, siger Anja Lundstrøm. Søren Elgaard har tidligere arbejdet sammen med Techcollege. De udførte udsmykningen af Hedegaardsiloen og portnerboligen på Eternitten sammen. Vråudstillingen i Kunstbygningen i Vrå har denne gang Vrå som sit tema. Søren Elgaards skitse hænger på Vråudstillingen i Kunstbygningen. Den er inspireret af den lutspillende gris fra Vrå Kirke   dog uden gris på gavlmaleriet.   Lutten er englenes instrument. Lut med gris er faktisk tegn på djævelskab, siger Søren Elgaard med et grin. I stedet har han føjet et hjørneornament til inspireret af et jomfru Mariamotiv fra kirken.   Lutten knytter sig jo også fint til byens musikalske traditioner, som udspringer fra Vrå Højskole, siger Søren Elgaard.   Jeg skal male lydhullets udskæringer i lutten, men de får lov til at male strengene. Det vanskeligste bliver den kurvede bund på lutten. Patrick Bengtson er i fuld gang med at grunde gavlen.   Det er en spændende opgave og det er rart at være ude i stedet for i skolepraktik på skolen, siger Patric Bengtson.   Jeg tror, at vi kan blande farverne. Vi har haft hele grundforløbet til lære det. Katrine Andreasen har prøvet det før. Hun var med til at lave murmaleri på Eternittens tvillingesilo.   Den gang var det lettere. Alle farver var blandet i forvejen. Her skal vi selv i gang, siger Katrine Andreasen. Foruden Patrick og Katrine deltager Julie Vilsgaard, Benjamin Bytygi og Daniel Immervoll. De gør Søren Elgaard opmærksom på, at lidt rødt trænger igennem grundmalingen.   Det gør ikke noget. Jeg tror ikke, at det kan ses, når vi begynder at male motivet, siger Søren Elgaard. Søren Elgaard har stor erfaring i murmalerier. Han lavede i 1991 murmaleri i Bryggergade i Hjørring, i 2011 murmaleri på Aalborg Katedralskole i samarbejde med skolen, i 2016 murmaleri, P.P. Hedegaard på Aalborg Havn, i 2017, Portnerboligen på Eternitten, Aalborg. Hans værker findes på Statens Museum for Kunst, Aros, Kunsten Aalborg, Skive Kunstmuseum, Vendsyssel Kunstmuseum, Randers Kunstmuseum, Kunstbygningen i Vrå. Janusbygningen i Tistrup."

# Do replacement
#text = text.replace("aa", "å").replace("oe", "ø").replace("ae", "æ").replace("Aa", "Å").replace("Oe", "Ø").replace("Ae", "Æ")

doc = nlp(text)
f = open("./output/output.txt", "w", encoding="utf-8")
for tok in doc:
    str1 = " ".join(tok._.lemmas)
    f.write(tok.text + " - " + tok.dep_ + " - " + tok.ent_type_ + " - lemmy[" + str1 + "], spaCy[" + tok.lemma_ + "]")
    f.write("\n")

#displacy.serve(doc, style="ent")