import enum

class RelationTypeConstants(str, enum.Enum):
    """
    Enumeration containing the constant values for the different relations and their types that is used in the ontology
    """
    # RDFS
    RDFS_RESOURCE = "rdfs:Resource"
    RDFS_CLASS = "rdfs:Class"
    RDFS_LITERAL = "rdfs:Literal"
    RDFS_DATATYPE = "rdfs:Datatype"
    RDFS_LANGSTRING = "rdfs:langString"
    RDFS_LABEL = "rdfs:label"
    RDFS_RANGE = "rdfs:range"
    RDFS_DOMAIN = "rdfs:domain"
    RDFS_SUB_CLASS_OF = "rdfs:subClassOf"
    RDFS_SUB_PROPERTY_OF = "rdfs:subPropertyOf"
    RDFS_COMMENT = "rdfs:comment"
    RDFS_CONTAINER = "rdfs:Container"
    RDFS_CONTAINER_MEMBERSHIP_PROPERTY = "rdfs:ContainerMembershipProperty"
    RDFS_MEMBER = "rdfs:member"
    RDFS_SEE_ALSO = "rdfs:seeAlso"
    RDFS_IS_DEFINED_BY = "rdfs:isDefinedBy"

    # RDF
    RDF_TYPE = "rdf:type"
    RDF_HTML = "rdf:HTML"
    RDF_XML_LITERAL = "rdf:XMLLiteral"
    RDF_PROPERTY = "rdf:Property"
    RDF_BAG = "rdf:Bag"
    RDF_SEQ = "rdf:Seq"
    RDF_ALT = "rdf:Alt"
    RDF_LIST = "rdf:List"
    RDF_FIRST = "rdf:first"
    RDF_REST = "rdf:rest"
    RDF_NIL = "rdf:nil"
    RDF_STATEMENT = "rdf:Statement"
    RDF_SUBJECT = "rdf:subject"
    RDF_PREDICATE = "rdf:predicate"
    RDF_OBJECT = "rdf:object"
    RDF_VALUE = "rdf:value"

    # OWL
    OWL_ALL_VALUES_FROM = "owl:allValuesFrom"
    OWL_BACKWARDS_COMPATIBLE_WITH = "owl:backwardCompatibleWith"
    OWL_CARDINALITY = "owl:cardinality"
    OWL_COMPLEMENT_OF = "owl:complementOf"
    OWL_DIFFERENT_FROM = "owl:differentFrom"
    OWL_DISJOINT_WITH = "owl:disjointWith"
    OWL_DISTINCT_MEMBERS = "owl:distinctMembers"
    OWL_EQUIVALENT_CLASS = "owl:equivalentClass"
    OWL_EQUIVALENT_PROPERTY = "owl:equivalentProperty"
    OWL_HAS_VALUE = "owl:hasValue"
    OWL_IMPORTS = "owl:imports"
    OWL_INCOMPATIBLE_WITH = "owl:incompatibleWith"
    OWL_INTERSECTION_OF = "owl:intersectionOf"
    OWL_INVERSE_OF = "owl:inverseOf"
    OWL_MAX_CARDINALITY = "owl:maxCardinality"
    OWL_MIN_CARDINALITY = "owl:minCardinality"
    OWL_ONE_OF = "owl:oneOf"
    OWL_ON_PROPERTY = "owl:onProperty"
    OWL_PRIOR_VERSION = "owl:priorVersion"
    OWL_SAME_AS = "owl:sameAs"
    OWL_SOME_VALUES_FROM = "owl:someValuesFrom"
    OWL_UNION_OF = "owl:unionOf"
    OWL_VERSION_INFO = "owl:versionInfo"
    OWL_RESTRICTION = "owl:Restriction"
    OWL_ONTOLOGY = "owl:Ontology"
    OWL_CLASS = "owl:Class"
    OWL_THING = "owl:Thing"
    OWL_ALL_DIFFERENT = "owl:AllDifferent"
    OWL_OBJECT_PROPERTY = "	owl:ObjectProperty"
    OWL_NAMED_INDIVIDUAL = "owl:NamedIndividual"

    #XSD
    XSD_ANY_URI = "xsd:anyURI"
    XSD_BASE_64_BINARY = "xsd:base64Binary"
    XSD_BOOLEAN = "xsd:boolean"
    XSD_BYTE = "xsd:byte"
    XSD_DATE = "xsd:date"
    XSD_DATE_TIME = "xsd:dateTime"
    XSD_DECIMAL = "xsd:decimal"
    XSD_DOUBLE = "xsd:double"
    XSD_FLOAT = "xsd:float"
    XSD_G_DAY = "xsd:gDay"
    XSD_G_MONTH = "xsd:gMonth"
    XSD_G_MONTH_DAY = "xsd:gMonthDay"
    XSD_G_YEAR = "xsd:gYear"
    XSD_G_YEAR_MONTH = "xsd:gYearMonth"
    XSD_HEX_BINARY = "xsd:hexBinary"
    XSD_INT = "xsd:int"
    XSD_INTEGER = "xsd:integer"
    XSD_LANGUAGE = "xsd:language"
    XSD_LONG = "xsd:long"
    XSD_NAME = "xsd:Name"
    XSD_NC_NAME = "xsd:NCName"
    XSD_NM_TOKEN = "xsd:NMTOKEN"
    XSD_NEGATIVE_INTEGER = "xsd:negativeInteger"
    XSD_NON_NEGATIVE_INTEGER = "xsd:nonNegativeInteger"
    XSD_NON_POSITIVE_INTEGER = "xsd:nonPositiveInteger"
    XSD_NORMALIZED_STRING = "xsd:normalizedString"
    XSD_POSITIVE_INTEGER = "xsd:positiveInteger"
    XSD_SHORT = "xsd:short"
    XSD_STRING = "xsd:string"
    XSD_TIME = "xsd:time"
    XSD_TOKEN = "xsd:token"
    XSD_UNSIGNED_BYTE = "xsd:unsignedByte"
    XSD_UNSIGNED_INT = "xsd:unsignedInt"
    XSD_UNSIGNED_LONG = "xsd:unsignedLong"
    XSD_UNSIGNED_SHORT = "xsd:unsignedShort"

    #KNOX
    KNOX_IS_PUBLISHED_BY = "knox:isPublishedBy"
    KNOX_MENTIONS = "knox:mentions"
    KNOX_IS_PUBLISHED_ON = "knox:isPublishedOn"
    KNOX_PUBLISHES = "knox:publishes"
    KNOX_EMAIL = "knox:Email"
    KNOX_DATE_MENTION = "knox:DateMention"
    KNOX_LINK = "knox:Link"
    KNOX_NAME = "knox:Name"
    KNOX_PUBLICATION_DAY = "knox:PublicationDay"
    KNOX_PUBLICATION_MONTH = "knox:PublicationMonth"
    KNOX_PUBLICATION_YEAR = "knox:PublicationYear"
    KNOX_ARTICLE_TITLE = "knox:ArticleTitle"
    KNOX_IS_WRITTEN_BY = "knox:isWrittenBy"
